package com.servora.android.data.session

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import androidx.core.content.edit
import com.servora.android.domain.model.IssuedSession
import dagger.hilt.android.qualifiers.ApplicationContext
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton
import kotlinx.serialization.SerializationException
import kotlinx.serialization.json.Json

/**
 * [SessionStorage] that keeps the session in an app-private preferences file as a single
 * AES-256-GCM ciphertext.
 *
 * Holding the session across process death means the refresh token outlives the process, so at-rest
 * encryption is required (`dev.md` §11, `docs/decisions/004-authentication-domain-model.md`). The key
 * is generated by and never leaves the Android Keystore; only the ciphertext and its random IV are
 * written, so a device backup or a root-level read of the preferences file does not expose the
 * credential. The keystore is the platform mechanism, so no crypto dependency is introduced
 * (`dev.md` §4); `androidx.security:security-crypto` is deprecated and adds nothing here.
 *
 * The file is one blob rather than one preference per field, so a session is written and replaced
 * atomically — a half-written token pair can never be restored.
 */
@Singleton
class EncryptedSessionStorage @Inject constructor(
    @ApplicationContext private val context: Context,
    private val json: Json,
) : SessionStorage {

    override fun read(): IssuedSession? {
        val preferences = preferences()
        val encodedIv = preferences.getString(KEY_IV, null) ?: return null
        val encodedCiphertext = preferences.getString(KEY_CIPHERTEXT, null) ?: return null
        return try {
            val plaintext = decrypt(decode(encodedIv), decode(encodedCiphertext))
            json.decodeFromString(StoredSessionDto.serializer(), plaintext.decodeToString())
                .toIssuedSession()
        } catch (failure: GeneralSecurityException) {
            // The key was invalidated or the ciphertext is unusable. A session that cannot be read
            // is not a session this build can trust, so it is dropped rather than left behind.
            clear()
            null
        } catch (failure: SerializationException) {
            clear()
            null
        } catch (failure: IllegalArgumentException) {
            // A malformed base64 value. Same reasoning as above.
            clear()
            null
        }
    }

    override fun write(session: IssuedSession) {
        val plaintext = json
            .encodeToString(StoredSessionDto.serializer(), session.toStoredSession())
            .encodeToByteArray()
        val encryption = encrypt(plaintext)
        preferences().edit(commit = true) {
            putString(KEY_IV, encode(encryption.iv))
            putString(KEY_CIPHERTEXT, encode(encryption.ciphertext))
        }
    }

    override fun clear() {
        preferences().edit(commit = true) {
            remove(KEY_IV)
            remove(KEY_CIPHERTEXT)
        }
    }

    private fun encrypt(plaintext: ByteArray): Encryption {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        return Encryption(iv = cipher.iv, ciphertext = cipher.doFinal(plaintext))
    }

    private fun decrypt(iv: ByteArray, ciphertext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv))
        return cipher.doFinal(ciphertext)
    }

    /**
     * The installation's session key, created on first use and returned from the keystore after.
     *
     * No user-authentication requirement is attached: field work must resume on a restarted process
     * without a biometric prompt, and the threat this protects against is the credential leaking
     * from storage, not an unlocked, physically-held device.
     */
    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                .build(),
        )
        return generator.generateKey()
    }

    private fun preferences() =
        context.getSharedPreferences(PREFERENCES_NAME, Context.MODE_PRIVATE)

    private fun encode(value: ByteArray): String = Base64.encodeToString(value, Base64.NO_WRAP)

    private fun decode(value: String): ByteArray = Base64.decode(value, Base64.NO_WRAP)

    private data class Encryption(val iv: ByteArray, val ciphertext: ByteArray)

    internal companion object {
        internal const val PREFERENCES_NAME = "servora.session"
        internal const val KEY_IV = "iv"
        internal const val KEY_CIPHERTEXT = "ciphertext"

        const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        const val KEY_ALIAS = "servora.session.key"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val KEY_SIZE_BITS = 256

        /** AES-GCM's authentication tag, which the JCA expects in bits. */
        const val GCM_TAG_LENGTH_BITS = 128
    }
}
