/**
 * The provider-neutral object-storage port (`ADR-013` D6.1).
 *
 * Evidence is business data (`BR-015`, `BR-027`) and it is stored and served by the backend, which is
 * the system of record (`BR-001`). The domain depends on this port, never on a provider SDK — the
 * same provider-neutrality `BR-019` applies to SMS (Twilio behind `SmsProvider`) and `ADR-008` to
 * email (Resend behind `EmailProvider`). `S3ObjectStorage` is the current implementation; replacing
 * it is a change to `StorageModule` and one file.
 *
 * `ADR-013` D6.4 and D6.5 decide what this port must not do: the database stores an **object key**,
 * never a URL and never a signed URL, and keys are generated by the API and stay provider-agnostic —
 * no host, no bucket, no provider vocabulary.
 */

/** The bytes of one stored object, with what the backend must tell a client about them. */
export interface StoredObject {
  /** The object's bytes. */
  readonly body: Buffer;
  /** The content type the object was stored with. */
  readonly contentType: string;
  readonly byteSize: number;
}

/** One object to store. */
export interface PutObjectInput {
  /** The provider-agnostic key (`jobPhotoObjectKey`), never a URL. */
  readonly key: string;
  readonly body: Buffer;
  /** The content type validated at the API boundary, not the one a client claimed. */
  readonly contentType: string;
}

/**
 * Stores and returns evidence objects.
 *
 * Only an implementation of this interface may reference a provider SDK.
 */
export interface ObjectStorage {
  /** Stores [input], replacing an object stored under the same key. */
  putObject(input: PutObjectInput): Promise<void>;

  /**
   * Returns the object stored under [key].
   *
   * Throws [ObjectNotFoundError] when the store holds nothing under it, and [ObjectStorageError]
   * when the request could not be completed.
   */
  getObject(key: string): Promise<StoredObject>;
}

/** Injection token for the bound `ObjectStorage`. */
export const OBJECT_STORAGE = Symbol('OBJECT_STORAGE');

/**
 * Raised when the store did not complete a request.
 *
 * It carries no provider-specific detail on purpose: everything above the port reacts to the failure
 * the same way, and a provider's error body is not part of Servora's contract (`dev.md` §7).
 */
export class ObjectStorageError extends Error {
  constructor() {
    super('The object store did not complete the request.');
    this.name = 'ObjectStorageError';
  }
}

/** Raised when nothing is stored under the requested key. */
export class ObjectNotFoundError extends Error {
  constructor() {
    super('No object is stored under that key.');
    this.name = 'ObjectNotFoundError';
  }
}

/** The content types Servora accepts as photo evidence, mapped to the key's extension. */
export const PHOTO_CONTENT_TYPES = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
} as const;

export type PhotoContentType = keyof typeof PHOTO_CONTENT_TYPES;

/**
 * The key one Job photo is stored under.
 *
 * It is generated by the API and names nothing about the provider or the bucket (`ADR-013` D6.5), so
 * the swap from MinIO to a provider is configuration. The organization and the Job appear as path
 * segments so that a store that is browsed by an operator is readable, and the photo's own id makes
 * the key unique and lets a retried upload overwrite the same object instead of leaving an orphan.
 */
export function jobPhotoObjectKey(input: {
  readonly organizationId: string;
  readonly jobId: string;
  readonly photoId: string;
  readonly contentType: PhotoContentType;
}): string {
  return [
    'evidence',
    'job-photos',
    input.organizationId,
    input.jobId,
    `${input.photoId}.${PHOTO_CONTENT_TYPES[input.contentType]}`,
  ].join('/');
}
