-- The clarification conversation of a follow-up Visit request (`BR-FV-012`).
--
-- A request the office returned for clarification is answered by its requester, and that exchange is
-- business history: the conversation is **request-scoped and append-only**, one row per message, so the
-- office's question and the technician's answer both survive the decision that follows them (`BR-067`,
-- `BR-FV-013`). A replying technician returns the request to `PENDING`, which is why the request's own
-- `review_note` is no longer the only place the exchange exists.
--
-- Generated by `db:generate`, with `meta/0018_snapshot.json` re-baselining the snapshot chain at this
-- migration (the chain had no snapshot for `0016_job_visit_lifecycle_redesign`; `0017_evidence_visit_link`
-- records the same step for the migration before this one).
CREATE TABLE "follow_up_visit_request_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"request_id" uuid NOT NULL,
	"author_membership_id" uuid NOT NULL,
	"body" text NOT NULL,
	"recorded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "follow_up_visit_request_messages_body_check" CHECK (length(btrim("follow_up_visit_request_messages"."body")) > 0)
);
--> statement-breakpoint
ALTER TABLE "follow_up_visit_request_messages" ADD CONSTRAINT "follow_up_visit_request_messages_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follow_up_visit_request_messages" ADD CONSTRAINT "follow_up_visit_request_messages_request_id_follow_up_visit_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."follow_up_visit_requests"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "follow_up_visit_request_messages" ADD CONSTRAINT "follow_up_visit_request_messages_author_membership_id_organization_members_id_fk" FOREIGN KEY ("author_membership_id") REFERENCES "public"."organization_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "follow_up_visit_request_messages_request_idx" ON "follow_up_visit_request_messages" USING btree ("organization_id","request_id","recorded_at");