// Servora database schema — foundation domain model.
//
// This is the authoritative Drizzle schema for the foundation domain:
// organizations, users, user profiles, organization memberships, customers and
// customer subtypes/contacts/addresses, plus the authentication credentials
// (auth sessions, refresh tokens, password-reset tokens).
//
// Conventions (see docs/domain/foundation-domain-model.md):
// - Every primary key is a UUID generated by PostgreSQL `gen_random_uuid()`.
// - Foreign keys use UUID and declare explicit ON DELETE behaviour.
// - Controlled vocabularies use VARCHAR + CHECK constraints (never native enums).
// - `created_at`/`updated_at` are `TIMESTAMPTZ NOT NULL DEFAULT NOW()`;
//   `updated_at` is additionally refreshed through Drizzle `$onUpdate` so the
//   application layer never writes a stale timestamp.
//
// Feature modules add their tables here so `drizzle-kit generate` always has a
// single schema entry point.
import { relations, sql } from 'drizzle-orm';
import type { AnyPgColumn } from 'drizzle-orm/pg-core';
import {
  boolean,
  check,
  date,
  index,
  inet,
  integer,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
  varchar,
} from 'drizzle-orm/pg-core';

const createdAt = () =>
  timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

const updatedAt = () =>
  timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    // Refresh on every UPDATE at the application layer using the database clock,
    // keeping the timestamp timezone-aware and independent of the API host.
    .$onUpdate(() => sql`now()`);

// ------------------------------------------------------------ organizations

export const organizations = pgTable(
  'organizations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: varchar('name', { length: 200 }).notNull(),
    email: varchar('email', { length: 320 }),
    phone: varchar('phone', { length: 50 }),
    status: varchar('status', { length: 20 }).notNull().default('ACTIVE'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    check('organizations_status_check', sql`${table.status} in ('ACTIVE', 'INACTIVE')`),
    index('organizations_status_idx').on(table.status),
    index('organizations_email_idx').on(table.email),
  ],
);

// ------------------------------------------------------------------- users

export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: varchar('email', { length: 320 }).notNull(),
    passwordHash: varchar('password_hash', { length: 255 }).notNull(),
    phone: varchar('phone', { length: 50 }),
    status: varchar('status', { length: 20 }).notNull().default('ACTIVE'),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    unique('users_email_unique').on(table.email),
    check(
      'users_status_check',
      sql`${table.status} in ('ACTIVE', 'INACTIVE', 'SUSPENDED')`,
    ),
  ],
);

// ------------------------------------------------------------ user_profiles

export const userProfiles = pgTable('user_profiles', {
  userId: uuid('user_id')
    .primaryKey()
    .references(() => users.id, { onDelete: 'cascade' }),
  firstName: varchar('first_name', { length: 100 }).notNull(),
  lastName: varchar('last_name', { length: 100 }).notNull(),
  displayName: varchar('display_name', { length: 201 }),
  phone: varchar('phone', { length: 50 }),
  avatarUrl: varchar('avatar_url', { length: 500 }),
  locale: varchar('locale', { length: 10 }).notNull().default('en-CA'),
  timezone: varchar('timezone', { length: 100 }).notNull().default('America/Toronto'),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});


// ------------------------------------------------------ organization_members

export const organizationMembers = pgTable(
  'organization_members',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: varchar('role', { length: 20 }).notNull(),
    status: varchar('status', { length: 20 }).notNull().default('ACTIVE'),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    unique('organization_members_organization_id_user_id_unique').on(
      table.organizationId,
      table.userId,
    ),
    check(
      'organization_members_role_check',
      sql`${table.role} in ('MANAGER', 'TECHNICIAN')`,
    ),
    check(
      'organization_members_status_check',
      sql`${table.status} in ('ACTIVE', 'INACTIVE')`,
    ),
    index('organization_members_organization_id_idx').on(table.organizationId),
    index('organization_members_user_id_idx').on(table.userId),
    index('organization_members_role_idx').on(table.role),
  ],
);

// --------------------------------------------------------------- customers

export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id, { onDelete: 'cascade' }),
    type: varchar('type', { length: 20 }).notNull(),
    displayName: varchar('display_name', { length: 255 }).notNull(),
    email: varchar('email', { length: 320 }),
    phone: varchar('phone', { length: 50 }),
    billingEmail: varchar('billing_email', { length: 320 }),
    billingPhone: varchar('billing_phone', { length: 50 }),
    notes: text('notes'),
    status: varchar('status', { length: 20 }).notNull().default('ACTIVE'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    check('customers_type_check', sql`${table.type} in ('INDIVIDUAL', 'COMPANY')`),
    check('customers_status_check', sql`${table.status} in ('ACTIVE', 'INACTIVE')`),
    index('customers_organization_id_idx').on(table.organizationId),
    index('customers_organization_type_idx').on(table.organizationId, table.type),
    index('customers_organization_status_idx').on(table.organizationId, table.status),
    index('customers_organization_display_name_idx').on(
      table.organizationId,
      table.displayName,
    ),
    index('customers_organization_email_idx').on(table.organizationId, table.email),
  ],
);

// --------------------------------------------------- customer_individuals

export const customerIndividuals = pgTable('customer_individuals', {
  customerId: uuid('customer_id')
    .primaryKey()
    .references(() => customers.id, { onDelete: 'cascade' }),
  firstName: varchar('first_name', { length: 100 }).notNull(),
  lastName: varchar('last_name', { length: 100 }).notNull(),
  dateOfBirth: date('date_of_birth'),
});

// ------------------------------------------------------ customer_companies

export const customerCompanies = pgTable('customer_companies', {
  customerId: uuid('customer_id')
    .primaryKey()
    .references(() => customers.id, { onDelete: 'cascade' }),
  legalName: varchar('legal_name', { length: 255 }).notNull(),
  businessName: varchar('business_name', { length: 255 }),
  taxNumber: varchar('tax_number', { length: 100 }),
});


// ------------------------------------------------------- customer_contacts

export const customerContacts = pgTable(
  'customer_contacts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    firstName: varchar('first_name', { length: 100 }).notNull(),
    lastName: varchar('last_name', { length: 100 }).notNull(),
    email: varchar('email', { length: 320 }),
    phone: varchar('phone', { length: 50 }),
    role: varchar('role', { length: 100 }),
    isPrimary: boolean('is_primary').notNull().default(false),
    isBillingContact: boolean('is_billing_contact').notNull().default(false),
    isJobContact: boolean('is_job_contact').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    index('customer_contacts_customer_id_idx').on(table.customerId),
    index('customer_contacts_email_idx').on(table.email),
  ],
);

// ------------------------------------------------------ customer_addresses

export const customerAddresses = pgTable(
  'customer_addresses',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id, { onDelete: 'cascade' }),
    type: varchar('type', { length: 20 }).notNull(),
    addressLine1: varchar('address_line1', { length: 255 }).notNull(),
    addressLine2: varchar('address_line2', { length: 255 }),
    city: varchar('city', { length: 100 }).notNull(),
    province: varchar('province', { length: 100 }).notNull(),
    postalCode: varchar('postal_code', { length: 20 }).notNull(),
    country: varchar('country', { length: 100 }).notNull().default('Canada'),
    isDefault: boolean('is_default').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    check(
      'customer_addresses_type_check',
      sql`${table.type} in ('SERVICE', 'BILLING', 'OTHER')`,
    ),
    index('customer_addresses_customer_id_idx').on(table.customerId),
    index('customer_addresses_type_idx').on(table.type),
  ],
);


// ------------------------------------------------------------- relations

export const organizationsRelations = relations(organizations, ({ many }) => ({
  members: many(organizationMembers),
  customers: many(customers),
}));

export const usersRelations = relations(users, ({ one, many }) => ({
  profile: one(userProfiles, {
    fields: [users.id],
    references: [userProfiles.userId],
  }),
  memberships: many(organizationMembers),
  sessions: many(authSessions),
  passwordResetTokens: many(passwordResetTokens),
  phoneOtpChallenges: many(phoneOtpChallenges),
}));

export const userProfilesRelations = relations(userProfiles, ({ one }) => ({
  user: one(users, {
    fields: [userProfiles.userId],
    references: [users.id],
  }),
}));

export const organizationMembersRelations = relations(
  organizationMembers,
  ({ one }) => ({
    organization: one(organizations, {
      fields: [organizationMembers.organizationId],
      references: [organizations.id],
    }),
    user: one(users, {
      fields: [organizationMembers.userId],
      references: [users.id],
    }),
  }),
);

export const customersRelations = relations(customers, ({ one, many }) => ({
  organization: one(organizations, {
    fields: [customers.organizationId],
    references: [organizations.id],
  }),
  individual: one(customerIndividuals, {
    fields: [customers.id],
    references: [customerIndividuals.customerId],
  }),
  company: one(customerCompanies, {
    fields: [customers.id],
    references: [customerCompanies.customerId],
  }),
  contacts: many(customerContacts),
  addresses: many(customerAddresses),
}));

export const customerIndividualsRelations = relations(
  customerIndividuals,
  ({ one }) => ({
    customer: one(customers, {
      fields: [customerIndividuals.customerId],
      references: [customers.id],
    }),
  }),
);

export const customerCompaniesRelations = relations(customerCompanies, ({ one }) => ({
  customer: one(customers, {
    fields: [customerCompanies.customerId],
    references: [customers.id],
  }),
}));

export const customerContactsRelations = relations(customerContacts, ({ one }) => ({
  customer: one(customers, {
    fields: [customerContacts.customerId],
    references: [customers.id],
  }),
}));

export const customerAddressesRelations = relations(customerAddresses, ({ one }) => ({
  customer: one(customers, {
    fields: [customerAddresses.customerId],
    references: [customers.id],
  }),
}));

// ------------------------------------------------------------ auth_sessions

// An authentication session is one signed-in client instance. A session belongs
// to the user (identity level), never to an organization: the same user may be a
// member of several organizations, and signing in happens once per device.
export const authSessions = pgTable(
  'auth_sessions',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    platform: varchar('platform', { length: 20 }).notNull(),
    deviceId: varchar('device_id', { length: 200 }).notNull(),
    deviceName: varchar('device_name', { length: 200 }),
    appVersion: varchar('app_version', { length: 50 }),
    ipAddress: inet('ip_address'),
    userAgent: varchar('user_agent', { length: 500 }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
  },
  (table) => [
    check('auth_sessions_platform_check', sql`${table.platform} in ('ANDROID', 'WEB')`),
    index('auth_sessions_user_id_idx').on(table.userId),
    index('auth_sessions_device_id_idx').on(table.deviceId),
    index('auth_sessions_expires_at_idx').on(table.expiresAt),
    // Supports the "does this user still have a usable session?" lookup. An index
    // predicate may only contain immutable expressions, so it is limited to the
    // revocation timestamp: `expires_at > now()` depends on the query time and
    // must stay out of the index, otherwise the index would silently stop
    // matching rows as time passes.
    index('auth_sessions_active_idx')
      .on(table.userId)
      .where(sql`${table.revokedAt} is null`),
  ],
);

// ------------------------------------------------------ auth_refresh_tokens

// Rotating refresh credential for one session. Only the SHA-256 hash of the
// opaque token is stored; the raw value exists only in the response handed to the
// client. `replacedByTokenId` records rotation so replay of a rotated token can
// be detected.
export const authRefreshTokens = pgTable(
  'auth_refresh_tokens',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    sessionId: uuid('session_id')
      .notNull()
      .references(() => authSessions.id, { onDelete: 'cascade' }),
    tokenHash: varchar('token_hash', { length: 255 }).notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    replacedByTokenId: uuid('replaced_by_token_id').references(
      (): AnyPgColumn => authRefreshTokens.id,
      { onDelete: 'set null' },
    ),
  },
  (table) => [
    unique('auth_refresh_tokens_token_hash_unique').on(table.tokenHash),
    index('auth_refresh_tokens_session_id_idx').on(table.sessionId),
    index('auth_refresh_tokens_expires_at_idx').on(table.expiresAt),
    index('auth_refresh_tokens_replaced_by_token_id_idx').on(table.replacedByTokenId),
  ],
);

// ----------------------------------------------------- password_reset_tokens

// A single-use password-reset credential. As with refresh tokens, only the hash
// is stored. `usedAt` marks consumption so a token cannot be replayed.
export const passwordResetTokens = pgTable(
  'password_reset_tokens',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    tokenHash: varchar('token_hash', { length: 255 }).notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    usedAt: timestamp('used_at', { withTimezone: true }),
    // Failed verification attempts against this credential. `BR-043` caps them at five,
    // so the count has to outlive the request that made it.
    attempts: integer('attempts').notNull().default(0),
  },
  (table) => [
    unique('password_reset_tokens_token_hash_unique').on(table.tokenHash),
    check('password_reset_tokens_attempts_check', sql`${table.attempts} >= 0`),
    index('password_reset_tokens_user_id_idx').on(table.userId),
    index('password_reset_tokens_expires_at_idx').on(table.expiresAt),
    // Supports "does this account still have a usable reset credential?" without
    // putting a non-immutable expression in the predicate (`ADR-004` D8).
    index('password_reset_tokens_outstanding_idx')
      .on(table.userId)
      .where(sql`${table.usedAt} is null`),
  ],
);

// ------------------------------------------------------ phone_otp_challenges

// One SMS one-time-password challenge (`BR-019`). A row is created per request and the
// next request supersedes it, so an invalidated challenge is provably unusable instead of
// being overwritten. Only the keyed digest of the code is stored (`BR-046`).
export const phoneOtpChallenges = pgTable(
  'phone_otp_challenges',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    codeHash: varchar('code_hash', { length: 255 }).notNull(),
    attempts: integer('attempts').notNull().default(0),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    consumedAt: timestamp('consumed_at', { withTimezone: true }),
  },
  (table) => [
    check('phone_otp_challenges_attempts_check', sql`${table.attempts} >= 0`),
    index('phone_otp_challenges_user_id_idx').on(table.userId),
    index('phone_otp_challenges_expires_at_idx').on(table.expiresAt),
    index('phone_otp_challenges_outstanding_idx')
      .on(table.userId)
      .where(sql`${table.consumedAt} is null`),
  ],
);

// ---------------------------------------------------- auth_rate_limit_events

// Rolling-window ledger for authentication attempts (`BR-045`), shared by every
// authentication entry point. The subject is stored as a keyed digest, so the table can
// count attempts per email address or phone number without retaining either of them.
export const authRateLimitEvents = pgTable(
  'auth_rate_limit_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    scope: varchar('scope', { length: 50 }).notNull(),
    subjectHash: varchar('subject_hash', { length: 64 }).notNull(),
    createdAt: createdAt(),
  },
  (table) => [
    check(
      'auth_rate_limit_events_scope_check',
      sql`${table.scope} in ('PASSWORD_RESET_REQUEST', 'SMS_OTP_REQUEST')`,
    ),
    index('auth_rate_limit_events_lookup_idx').on(
      table.scope,
      table.subjectHash,
      table.createdAt,
    ),
  ],
);

// ----------------------------------------------------------- auth relations

export const authSessionsRelations = relations(authSessions, ({ one, many }) => ({
  user: one(users, {
    fields: [authSessions.userId],
    references: [users.id],
  }),
  refreshTokens: many(authRefreshTokens),
}));

export const authRefreshTokensRelations = relations(authRefreshTokens, ({ one }) => ({
  session: one(authSessions, {
    fields: [authRefreshTokens.sessionId],
    references: [authSessions.id],
  }),
  // The rotation successor, so a reused token can be traced back to its chain.
  replacedByToken: one(authRefreshTokens, {
    fields: [authRefreshTokens.replacedByTokenId],
    references: [authRefreshTokens.id],
    relationName: 'auth_refresh_tokens_replacement',
  }),
}));

export const passwordResetTokensRelations = relations(passwordResetTokens, ({ one }) => ({
  user: one(users, {
    fields: [passwordResetTokens.userId],
    references: [users.id],
  }),
}));

export const phoneOtpChallengesRelations = relations(
  phoneOtpChallenges,
  ({ one }) => ({
    user: one(users, {
      fields: [phoneOtpChallenges.userId],
      references: [users.id],
    }),
  }),
);

